<h1>Tensor Definition: </h1>
In deep learning, a Tensor is a multi-dimensional array of numbers. It is the fundamental data structure used by frameworks like PyTorch and TensorFlow. While a matrix is a 2D grid, a tensor can have any number of dimensions.

<h2>Rank (ndims): </h2> The number of axes/dimensions. A color image is typically a Rank-3 tensor (Height, Width, Color Channels).Shape: A tuple of integers that describes how many elements the tensor has along each axis.Example: An image of $28 \times 28$ pixels has a shape of (28, 28).Data Type (dtype): Tensors usually contain float32, int64, or uint8. Deep learning models almost exclusively use float32 or float16 for gradients and weights.

<h1>Tensor Operations</h1>

<h3>Creation and Initialization</h3>

In [1]:
import torch

In [17]:
l1 = [3,4,5] #way 1 of converting a list to  tensor
test1 = torch.tensor(l1)
print(test1)

tensor([3, 4, 5])


In [18]:
t1 = torch.tensor([1, 2, 3]) #way 2 of converting a list to  tensor
print(t1)

tensor([1, 2, 3])


In [19]:
t2 = torch.randn(3, 4) #create a tensor of dimension 3x4
t2 #(random numbers samples from normal dist with mean = 0 and var =1)
#we can use this to assign initial random weights to the neurons in the NN

tensor([[-0.6393,  0.0827,  1.5868,  1.7748],
        [ 0.1146, -0.6380,  0.3269, -0.7801],
        [ 0.6129, -0.7639,  0.7324, -0.6224]])

In [20]:
zeros = torch.zeros(4, 4)
zeros #to assign weight 0 to all the NN initally

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
two = torch.twos(3,3)
two # there is no TWO's in pytorch

AttributeError: module 'torch' has no attribute 'twoes'

In [22]:
t2

tensor([[-0.6393,  0.0827,  1.5868,  1.7748],
        [ 0.1146, -0.6380,  0.3269, -0.7801],
        [ 0.6129, -0.7639,  0.7324, -0.6224]])

In [13]:
five = torch.full((6, 6), 5)
five

tensor([[5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5]])

In [23]:
t2.shape #to tell dimensions

torch.Size([3, 4])

In [24]:
t2_reshaped = torch.reshape(t2, (4,3)) 

In [25]:
t2_reshaped #it has put the tensor in row major manner

tensor([[-0.6393,  0.0827,  1.5868],
        [ 1.7748,  0.1146, -0.6380],
        [ 0.3269, -0.7801,  0.6129],
        [-0.7639,  0.7324, -0.6224]])

In [ ]:
t2_reshaped = torch.reshape(t2, (2,6))
t2_reshaped

tensor([[-0.6393,  0.0827,  1.5868,  1.7748,  0.1146, -0.6380],
        [ 0.3269, -0.7801,  0.6129, -0.7639,  0.7324, -0.6224]])

In [31]:
t2_flattened = torch.flatten(t2) #flatten = reshape(e, 1)

In [32]:
t2_flattened #flatten makes it 12 x1 (12 or e for the actual number of elements -> n x m = e)

tensor([-0.6393,  0.0827,  1.5868,  1.7748,  0.1146, -0.6380,  0.3269, -0.7801,
         0.6129, -0.7639,  0.7324, -0.6224])

In [33]:
t2_batch = t2.unsqueeze(0)

In [36]:
t2_batch.shape #adds a new dimension

torch.Size([1, 3, 4])

In [38]:
t2_reshaped = torch.reshape(t2, (4,3)) t2_batch2 = t2_batch.unsqueeze(0)
t2_batch2.shape

torch.Size([1, 1, 3, 4])

In [ ]:
t3_channels = t2.unsqueeze()

In [24]:
t2_batch_channel = t2_batch.unsqueeze(0)

In [25]:
t2_batch_channel.shape

torch.Size([1, 1, 3, 4])

<h1>Tasks</h1>

<h3>Task: 1 </h3> Create a random Rank-3 tensor of shape (3, 128, 128) representing an RGB image. 2. Convert it to grayscale by averaging the channel dimension (reducing Rank 3 to Rank 2). 3. "Flatten" the image into a 1D vector. 4. Add a "Batch" dimension and Channel dimention to the start so it becomes shape (1, 1, 128, 128).

In [48]:
t = torch.randn(3, 128, 128) #1

In [49]:
t.shape

torch.Size([3, 128, 128])

In [57]:
t2 = torch.mean(t, 0) #2
t2.shape

torch.Size([128, 128])

In [59]:
t2.dim()

2

In [63]:
t3 = torch.flatten(t2) #3
t3.shape

torch.Size([16384])

In [68]:
t4 = t2.unsqueeze(0) #4
t4.shape

torch.Size([1, 128, 128])

In [69]:
t4_batch = t4.unsqueeze(0)
t4_batch.shape

torch.Size([1, 1, 128, 128])

<h1>Data Loaders</h1>

In [1]:
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Define the transformation pipeline
transform = transforms.Compose([ 
    transforms.ToTensor(),#to make sure whatever ops happen will havppen on tensor we convert pillow arry to tensor
    transforms.Normalize((0.5,), (0.5,)) #mean is 0.5 and sd is 0.5 
])

In [2]:
# Download and load the training data
train_set = datasets.MNIST(root='./data', train=True, download=True, transform=transform)

# Download and load the test data
test_set = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

100.0%
100.0%
100.0%
100.0%


In [3]:
train_loader = DataLoader(train_set, batch_size=64, shuffle=True) #shuffle will make sure at each iteration the model will see different sequence of samples. 
test_loader = DataLoader(test_set, batch_size=64, shuffle=False)# like 1,2,3 then 3,2,1 then 2,3,1 etc

In [4]:
# Get one batch of data
images, labels = next(iter(train_loader)) #next is the one who iterates over the images and allows to you to extract info from it
#iter is a waiter who serves the image one by one, it does not iterate 
print(f"Batch Image Shape: {images.shape}") 
print(f"Batch Label Shape: {labels.shape}") 

Batch Image Shape: torch.Size([64, 1, 28, 28])
Batch Label Shape: torch.Size([64])


<h3>Task2:</h3> Print the total number of batches in train_loader. 2. Extract the first image from the first batch. 3. Display its label. 4. Calculate the total number of images in the training set using only the DataLoader.

In [7]:
number = len(train_loader) #1
print(f"Total Number of Batches: {number}")

Total Number of Batches: 938


In [13]:
first_image = images[0].shape #2
first_image

torch.Size([1, 28, 28])

In [15]:
first_label = labels[0] #3
first_label #this means the class is 7, "The neural network should treat this image as belonging to category #7."

tensor(7)

In [16]:
labels[0].item()

7

In [ ]:
total = len(train_loader.dataset) #4 
total

60000